- name: install and run script
  hosts: web
  tasks:
    - name: install nginix
      ansible.builtin.dnf:
         name: nginx
         state: latest
    - name: start nginx
      ansible.builtin.service:
         name: nginx
         state: started
         enabled: yes

