- name: PLAY-1
  hosts: localhost
  tasks:
    vars:
      course: "Terraform"
      Trainer: "Shiva"
      Duration: "128"
    tasks:
    ansible.builtin.debug:
    msg: "Hi iam Learning {{course}} from {{Trainer}} Duration {{Duration}}"



