- name: variables at task
  hosts: localhost
  tasks:
    - name: print Inforamtion
      vars:
        course: "Python"
        Trainer: "James"
        Duration: "200"
      ansible.builtin.debug:  
      msg: "Hi, welcome to {{course}} Learning from {{Trainer}} Duration is {{Duration}}"
        
  