- name: variables at task
  hosts: localhost
  vars:
    course: "Python"
    Trainer: "James"
    Duration: "200"
  tasks:
  - name: print Inforamtion
    vars:
     course: Devops
    ansible.builtin.debug:  
      msg: "Hi, welcome to {{course}} Learning from {{Trainer}} Duration is {{Duration}}"
        
  