- name: variables from file
  hosts: localhost
  vars_File:
  - var-file
  tasks:
  - name: Print Inforamtion
    ansible.builtin.debug:
    msg: "Hi welcome to {{course}} Traine is {{Trainer}} Duration is {{Duration}}"