- name: variables from file
  hosts: localhost
  vars_files:
  - var-file.yaml
  tasks:
    - name: Print Inforamtion
      ansible.builtin.debug:
        msg: "Hi welcome to {{course}} Traine is {{Trainer}} Duration is {{Duration}}"