- name: variables from user prompt
  hosts: localhost
  Vars_prompt:
  - name: USERNAME
    prompt: Please Enter user name
    Private: false
  - name: PASSWORD
    prompt: Please Enter PASSWORD
    Private: false
  tasks:
  - name: Please print Inforamtion
    ansible.builtin.debug:
      msg: "Hi, My user Name is {{USERNAME}} and Password is {{PASSWORD}}"