- name: variables
  hosts: web
  vars_prompt:
  - name: USERNAME
    prompt: Please enter your user name
    private: false
  - name: PASSWORD
    prompt: Please enter you Password
    private: false
  tasks:
    - name: user information
      ansible.builtin.debug:
        msg: "hi userName is :{{USERNAME}}. password IS:{{PASSWORD}}"


  
