- name: variables
  hosts: localhost
  tasks:
    - name: Print Inforamtion
      ansible.builtin.debug:
        msg: "Hi,iam Learning {{course}} from {{Trainer}} Duration {{Duration}}. Timeings are:${{Timeings}}"
        

