- name: filters
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{course  | default ('Ansible')}}"

- name: convert upper
  hosts: localhost
  vars: 
      Gretings: Morning"
  tasks:
  - name: Print Info
    ansible.builtin.debug:
      msg: "{{Gretings | upper}}"