- name: filters
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{course  | default ('Ansible')}}"

- name: convert upper
  hosts: localhost
  vars: 
      Gretings: Morning"
  tasks:
  - name: Print Info
    ansible.builtin.debug:
      msg: "{{Gretings | upper}}"


- name: duplicates
  hosts: localhost
  vars:
      numbers: [1,2,3,3,4,4,5,5,6,7,]
  tasks:
  - name: Remove duplicates
    ansible.builtin.debug:
        msg: "{{numbers | unique}}"

- name: age
  hosts: localhost
  vars:
      ages: [1,2,3,3,4,4,5,5,6,7,]
  tasks:
  - name: Numbers
    ansible.builtin.debug:
        msg: "age of min:{{ages | min}}, age of max:{{ages | max}}"


- name: dictvalues
  hosts: localhost
  vars: 
    dictval:
      course: devops
      trainer: shivakumar
      time: 180
  tasks:
  - name: beforeconvert
    ansible.builtin.debug:
        msg: "values before: {{dictval}}"
  - name: afterconvert
    ansible.builtin.debug:
        msg: "values after: {{dictval | dict2iteams}}"
        

