- name: filters
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{course  | default ('Ansible')}}"

- name: convert upper
  hosts: localhost
  vars: 
      Gretings: Morning"
  tasks:
  - name: Print Info
    ansible.builtin.debug:
      msg: "{{Gretings | upper}}"


- name: duplicates
  hosts: localhost
  vars:
      numbers: [1,2,3,3,4,4,5,5,6,7,]
  tasks:
  - name: Remove duplicates
    ansible.builtin.debug:
        msg: "{{numbers | unique}}"

- name: duplicates
  hosts: localhost
  vars:
      numbers: [1,2,3,3,4,4,5,5,6,7,]
  tasks:
  - name: Remove duplicates
    ansible.builtin.debug:
        msg: "{{numbers | Min}}"

- name: duplicates
  hosts: localhost
  vars:
      numbers: [1,2,3,3,4,4,5,5,6,7,]
  tasks:
  - name: Remove duplicates
    ansible.builtin.debug:
        msg: "{{numbers | Max}}"

