- name: demo on loop
  hosts: localhost
  tasks:
  - name : toolsinfo
    ansible.builtin.debug:
      msg:  "this are list of iteams:{{items}}"
      loop: 
      - linux
      - sheel
      - script