- name: demo on loop
  hosts: localhost
  vars:
      items:
      - java
      - Python
      - web
  tasks:
  - name: print info
    ansible.builtin.debug:
      msg: "this are list of{{items}}"
    loop:
      - java
      - Python
      - web

