- name: demo on loop
  hosts: localhost
  vars:
      items:
      - linux
      - sheel
      - script
  tasks:
  - name: print info
    ansible.builtin.debug:
      msg: "this are list of{{items}}"
    loop:
      - linux
      - sheel
      - script

