- name: install packages
  hosts: localhost
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: latest
    loop: 
    - { name: 'mysql' , state: 'absent'},
    - { name: 'java' , state: 'absent'},
    - { name: 'nginx' , state: 'absent'},
    - { name: 'git' , state: 'latest'},