- name: install packages
  hosts: localhost
  become: true
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop: 
    - { name: 'mysql' , state: 'absent'}
    - { name: 'java' , state: 'absent'}
    - { name: 'nginx' , state: 'absent'}
    - { name: 'git' , state: 'latest'}